In [1]:
#1).add two matrix
import numpy as np  
mat1 = np.matrix([[7, 8, 9], [3, -1, 17], [15, 10, 21]])  
mat2 = np.matrix([[9, -18, 27], [11, 22, 33], [13, -26, 39]])  
mat3 = mat1 + mat2    
print("The matrix addition is: ")  
print(mat3) 

The matrix addition is: 
[[ 16 -10  36]
 [ 14  21  50]
 [ 28 -16  60]]


In [5]:
#multiply two  matrix
import numpy as np  
mat1 = np.matrix([[7, 8, 9], [3, -1, 17], [15, 10, 21]])  
mat2 = np.matrix([[9, -18, 27], [11, 22, 33], [13, -26, 39]]) 
mat3=mat1*mat2
print("The matrix multiplication is: ")  
print(mat3)

The matrix multiplication is: 
[[ 268 -184  804]
 [ 237 -518  711]
 [ 518 -596 1554]]


In [6]:
#transpose a matrix
import numpy as np  
mat1 = np.matrix([[7, 8, 9], [3, -1, 17], [15, 10, 21]])
mat3=mat1.T
print("The transpose of matrix  is: ")  
print(mat3)

The transpose of matrix  is: 
[[ 7  3 15]
 [ 8 -1 10]
 [ 9 17 21]]


In [10]:
#sort words
words = input("Enter a string: ")    
words = words.split()   
words.sort()    
for i in words:  
    print(i) 

Enter a string: gfg greg rtqe hef
gfg
greg
hef
rtqe


In [13]:
#punctuation
punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
words = input("Enter a string: ")
removed = ""
for char in words:
    if char not in punctuation:
         removed= removed + char
print(removed)

Enter a string: %#$%  QGqGQ$#^^ RE$%#$@ FEGFU#I*$^%&
  QGqGQ RE FEGFUI
